---
title: "Trendecon Austria Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: 
      version: 4
      bootswatch: flatly
    social: menu
    vertical_layout: scroll
    navbar:
      - {icon: "fa-github", 
         title: "Dashboard", 
         href: "https://github.com/FelixZangerl/dashboard", align: right, target: blank}
      - {title: "R package", href: "https://trendecon.github.io/trendecon/", align: right, target: blank}    
---

```{r setup, include=FALSE}
library(flexdashboard)
library(htmlwidgets)
library(dygraphs)
library(readr)
library(tsbox)
library(xts)
library(dplyr)
library(knitr)

today <- as.character(Sys.Date())
```

This project is based on the work of [trendecon](https://www.trendecon.org)

Row
-----------------------------------------------------------------------

### Perceived Economic Situation

```{r, eval=T}
economic_sentiment <- read_csv("https://raw.githubusercontent.com/FelixZangerl/gsv_data/main/raw/at/economic_sentiment_sa.csv") %>%
  select(time,value) %>%
  mutate(value = -value) %>%
  ts_xts()

dygraph(economic_sentiment,group = "keywords")%>%
  dyAxis("x", drawGrid = FALSE)%>%
  dySeries("value", label = "Index")%>%
    dyEvent("2020-3-16", "Lockdown #1", labelLoc = "bottom")%>%
    dyEvent("2020-5-1", "End of Lockdown #1", labelLoc = "bottom")%>%
    dyEvent("2020-9-14", "Mandatory wearing of masks", labelLoc = "bottom")%>%
    dyEvent("2020-9-21", "Lockdown 'light'", labelLoc = "bottom")%>%
    dyEvent("2020-11-17", "Lockdown #2", labelLoc = "bottom")%>%
    dyEvent("2020-12-6", "End of Lockdown #2", labelLoc = "bottom")%>%
    dyEvent("2020-12-26", "Lockdown #3", labelLoc = "bottom")%>%
    dyEvent("2021-2-7", "End of Lockdown #3", labelLoc = "bottom")%>%
    dyEvent("2021-5-19", "Easing measures - gastronomy, tourism, sports", labelLoc = "bottom")%>%
    dyEvent("2021-6-10", "Easing measures - less social distancing", labelLoc = "bottom")%>%
    dyEvent("2021-7-01", "Easing measures - night gastronomy", labelLoc = "bottom")%>%

      dyRangeSelector(dateWindow = c("2020-01-01", today))%>%
      dyOptions(useDataTimezone = TRUE)
```


Row
-----------------------------------------------------------------------

### Clothing

```{r}
clothing <- read_csv("https://raw.githubusercontent.com/FelixZangerl/gsv_data/main/raw/at/clothing_sa.csv") %>%
  select(time,value) %>%
  ts_xts()

dygraph(clothing,group = "keywords")%>%
  dyAxis("x", drawGrid = FALSE)%>%
  dySeries("value", label = "Index")%>%
    dyEvent("2020-3-16", "Lockdown #1", labelLoc = "bottom")%>%
    dyEvent("2020-5-1", "End of Lockdown #1", labelLoc = "bottom")%>%
    dyEvent("2020-9-14", "Mandatory wearing of masks", labelLoc = "bottom")%>%
    dyEvent("2020-9-21", "Lockdown 'light'", labelLoc = "bottom")%>%
    dyEvent("2020-11-17", "Lockdown #2", labelLoc = "bottom")%>%
    dyEvent("2020-12-6", "End of Lockdown #2", labelLoc = "bottom")%>%
    dyEvent("2020-12-26", "Lockdown #3", labelLoc = "bottom")%>%
    dyEvent("2021-2-7", "End of Lockdown #3", labelLoc = "bottom")%>%
    dyEvent("2021-5-19", "Easing measures - gastronomy, tourism, sports", labelLoc = "bottom")%>%
    dyEvent("2021-6-10", "Easing measures - less social distancing", labelLoc = "bottom")%>%
    dyEvent("2021-7-01", "Easing measures - night gastronomy", labelLoc = "bottom")%>%
      dyRangeSelector(dateWindow = c("2020-01-01", today))%>%
      dyOptions(useDataTimezone = TRUE)
```

Row
-----------------------------------------------------------------------

### Home Office

```{r}
home_office <- read_csv("https://raw.githubusercontent.com/FelixZangerl/gsv_data/main/raw/at/home_office_sa.csv") %>%
  select(time,value) %>%
  ts_xts()

dygraph(home_office,group = "keywords")%>%
  dyAxis("x", drawGrid = FALSE)%>%
  dySeries("value", label = "Index")%>%
    dyEvent("2020-3-16", "Lockdown #1", labelLoc = "bottom")%>%
    dyEvent("2020-5-1", "End of Lockdown #1", labelLoc = "bottom")%>%
    dyEvent("2020-9-14", "Mandatory wearing of masks", labelLoc = "bottom")%>%
    dyEvent("2020-9-21", "Lockdown 'light'", labelLoc = "bottom")%>%
    dyEvent("2020-11-17", "Lockdown #2", labelLoc = "bottom")%>%
    dyEvent("2020-12-6", "End of Lockdown #2", labelLoc = "bottom")%>%
    dyEvent("2020-12-26", "Lockdown #3", labelLoc = "bottom")%>%
    dyEvent("2021-2-7", "End of Lockdown #3", labelLoc = "bottom")%>%
    dyEvent("2021-5-19", "Easing measures - gastronomy, tourism, sports", labelLoc = "bottom")%>%
    dyEvent("2021-6-10", "Easing measures - less social distancing", labelLoc = "bottom")%>%
    dyEvent("2021-7-01", "Easing measures - night gastronomy", labelLoc = "bottom")%>%
      dyRangeSelector(dateWindow = c("2020-01-01", today))%>%
      dyOptions(useDataTimezone = TRUE)
```

Row
-----------------------------------------------------------------------

### Gardening

```{r}
gardening <- read_csv("https://raw.githubusercontent.com/FelixZangerl/gsv_data/main/raw/at/gardening_sa.csv") %>%
  select(time,value) %>%
  ts_xts()

dygraph(gardening,group = "keywords")%>%
  dyAxis("x", drawGrid = FALSE)%>%
  dySeries("value", label = "Index")%>%
    dyEvent("2020-3-16", "Lockdown #1", labelLoc = "bottom")%>%
    dyEvent("2020-5-1", "End of Lockdown #1", labelLoc = "bottom")%>%
    dyEvent("2020-9-14", "Mandatory wearing of masks", labelLoc = "bottom")%>%
    dyEvent("2020-9-21", "Lockdown 'light'", labelLoc = "bottom")%>%
    dyEvent("2020-11-17", "Lockdown #2", labelLoc = "bottom")%>%
    dyEvent("2020-12-6", "End of Lockdown #2", labelLoc = "bottom")%>%
    dyEvent("2020-12-26", "Lockdown #3", labelLoc = "bottom")%>%
    dyEvent("2021-2-7", "End of Lockdown #3", labelLoc = "bottom")%>%
    dyEvent("2021-5-19", "Easing measures - gastronomy, tourism, sports", labelLoc = "bottom")%>%
    dyEvent("2021-6-10", "Easing measures - less social distancing", labelLoc = "bottom")%>%
    dyEvent("2021-7-01", "Easing measures - night gastronomy", labelLoc = "bottom")%>%
      dyRangeSelector(dateWindow = c("2020-01-01", today))%>%
      dyOptions(useDataTimezone = TRUE)
```

Row
-----------------------------------------------------------------------

### Food Delivery

```{r}
food_delivery <- read_csv("https://raw.githubusercontent.com/FelixZangerl/gsv_data/main/raw/at/food_delivery_sa.csv") %>%
  select(time,value) %>%
  ts_xts()

dygraph(food_delivery,group = "keywords")%>%
  dyAxis("x", drawGrid = FALSE)%>%
  dySeries("value", label = "Index")%>%
    dyEvent("2020-3-16", "Lockdown #1", labelLoc = "bottom")%>%
    dyEvent("2020-5-1", "End of Lockdown #1", labelLoc = "bottom")%>%
    dyEvent("2020-9-14", "Mandatory wearing of masks", labelLoc = "bottom")%>%
    dyEvent("2020-9-21", "Lockdown 'light'", labelLoc = "bottom")%>%
    dyEvent("2020-11-17", "Lockdown #2", labelLoc = "bottom")%>%
    dyEvent("2020-12-6", "End of Lockdown #2", labelLoc = "bottom")%>%
    dyEvent("2020-12-26", "Lockdown #3", labelLoc = "bottom")%>%
    dyEvent("2021-2-7", "End of Lockdown #3", labelLoc = "bottom")%>%
    dyEvent("2021-5-19", "Easing measures - gastronomy, tourism, sports", labelLoc = "bottom")%>%
    dyEvent("2021-6-10", "Easing measures - less social distancing", labelLoc = "bottom")%>%
    dyEvent("2021-7-01", "Easing measures - night gastronomy", labelLoc = "bottom")%>%
      dyRangeSelector(dateWindow = c("2020-01-01", today))%>%
      dyOptions(useDataTimezone = TRUE)
```

Row
-----------------------------------------------------------------------

### Cultural

```{r}
cultural <- read_csv("https://raw.githubusercontent.com/FelixZangerl/gsv_data/main/raw/at/cultural_sa.csv") %>%
  select(time,value) %>%
  ts_xts()

dygraph(cultural,group = "keywords")%>%
  dyAxis("x", drawGrid = FALSE)%>%
  dySeries("value", label = "Index")%>%
    dyEvent("2020-3-16", "Lockdown #1", labelLoc = "bottom")%>%
    dyEvent("2020-5-1", "End of Lockdown #1", labelLoc = "bottom")%>%
    dyEvent("2020-9-14", "Mandatory wearing of masks", labelLoc = "bottom")%>%
    dyEvent("2020-9-21", "Lockdown 'light'", labelLoc = "bottom")%>%
    dyEvent("2020-11-17", "Lockdown #2", labelLoc = "bottom")%>%
    dyEvent("2020-12-6", "End of Lockdown #2", labelLoc = "bottom")%>%
    dyEvent("2020-12-26", "Lockdown #3", labelLoc = "bottom")%>%
    dyEvent("2021-2-7", "End of Lockdown #3", labelLoc = "bottom")%>%
    dyEvent("2021-5-19", "Easing measures - gastronomy, tourism, sports", labelLoc = "bottom")%>%
    dyEvent("2021-6-10", "Easing measures - less social distancing", labelLoc = "bottom")%>%
    dyEvent("2021-7-01", "Easing measures - night gastronomy", labelLoc = "bottom")%>%
      dyRangeSelector(dateWindow = c("2020-01-01", today))%>%
      dyOptions(useDataTimezone = TRUE)
```

Row
-----------------------------------------------------------------------

### Travel

```{r}
travel <- read_csv("https://raw.githubusercontent.com/FelixZangerl/gsv_data/main/raw/at/travel_sa.csv") %>%
  select(time,value) %>%
  ts_xts()

dygraph(travel,group = "keywords")%>%
  dyAxis("x", drawGrid = FALSE)%>%
  dySeries("value", label = "Index")%>%
    dyEvent("2020-3-16", "Lockdown #1", labelLoc = "bottom")%>%
    dyEvent("2020-5-1", "End of Lockdown #1", labelLoc = "bottom")%>%
    dyEvent("2020-9-14", "Mandatory wearing of masks", labelLoc = "bottom")%>%
    dyEvent("2020-9-21", "Lockdown 'light'", labelLoc = "bottom")%>%
    dyEvent("2020-11-17", "Lockdown #2", labelLoc = "bottom")%>%
    dyEvent("2020-12-6", "End of Lockdown #2", labelLoc = "bottom")%>%
    dyEvent("2020-12-26", "Lockdown #3", labelLoc = "bottom")%>%
    dyEvent("2021-2-7", "End of Lockdown #3", labelLoc = "bottom")%>%
    dyEvent("2021-5-19", "Easing measures - gastronomy, tourism, sports", labelLoc = "bottom")%>%
    dyEvent("2021-6-10", "Easing measures - less social distancing", labelLoc = "bottom")%>%
    dyEvent("2021-7-01", "Easing measures - night gastronomy", labelLoc = "bottom")%>%
      dyRangeSelector(dateWindow = c("2020-01-01", today))%>%
      dyOptions(useDataTimezone = TRUE)
```

Row
-----------------------------------------------------------------------

### Mobility

```{r}
mobility <- read_csv("https://raw.githubusercontent.com/FelixZangerl/gsv_data/main/raw/at/mobility_sa.csv") %>%
  select(time,value) %>%
  ts_xts()

dygraph(mobility,group = "keywords")%>%
  dyAxis("x", drawGrid = FALSE)%>%
  dySeries("value", label = "Index")%>%
    dyEvent("2020-3-16", "Lockdown #1", labelLoc = "bottom")%>%
    dyEvent("2020-5-1", "End of Lockdown #1", labelLoc = "bottom")%>%
    dyEvent("2020-9-14", "Mandatory wearing of masks", labelLoc = "bottom")%>%
    dyEvent("2020-9-21", "Lockdown 'light'", labelLoc = "bottom")%>%
    dyEvent("2020-11-17", "Lockdown #2", labelLoc = "bottom")%>%
    dyEvent("2020-12-6", "End of Lockdown #2", labelLoc = "bottom")%>%
    dyEvent("2020-12-26", "Lockdown #3", labelLoc = "bottom")%>%
    dyEvent("2021-2-7", "End of Lockdown #3", labelLoc = "bottom")%>%
    dyEvent("2021-5-19", "Easing measures - gastronomy, tourism, sports", labelLoc = "bottom")%>%
    dyEvent("2021-6-10", "Easing measures - less social distancing", labelLoc = "bottom")%>%
    dyEvent("2021-7-01", "Easing measures - night gastronomy", labelLoc = "bottom")%>%
      dyRangeSelector(dateWindow = c("2020-01-01", today))%>%
      dyOptions(useDataTimezone = TRUE)
```

Row
-----------------------------------------------------------------------

### Jewelry

```{r}
jewelry <- read_csv("https://raw.githubusercontent.com/FelixZangerl/gsv_data/main/raw/at/luxury_sa.csv") %>%
  select(time,value) %>%
  ts_xts()

dygraph(jewelry,group = "keywords")%>%
  dyAxis("x", drawGrid = FALSE)%>%
  dySeries("value", label = "Index")%>%
    dyEvent("2020-3-16", "Lockdown #1", labelLoc = "bottom")%>%
    dyEvent("2020-5-1", "End of Lockdown #1", labelLoc = "bottom")%>%
    dyEvent("2020-9-14", "Mandatory wearing of masks", labelLoc = "bottom")%>%
    dyEvent("2020-9-21", "Lockdown 'light'", labelLoc = "bottom")%>%
    dyEvent("2020-11-17", "Lockdown #2", labelLoc = "bottom")%>%
    dyEvent("2020-12-6", "End of Lockdown #2", labelLoc = "bottom")%>%
    dyEvent("2020-12-26", "Lockdown #3", labelLoc = "bottom")%>%
    dyEvent("2021-2-7", "End of Lockdown #3", labelLoc = "bottom")%>%
    dyEvent("2021-5-19", "Easing measures - gastronomy, tourism, sports", labelLoc = "bottom")%>%
    dyEvent("2021-6-10", "Easing measures - less social distancing", labelLoc = "bottom")%>%
    dyEvent("2021-7-01", "Easing measures - night gastronomy", labelLoc = "bottom")%>%
      dyRangeSelector(dateWindow = c("2020-01-01", today))%>%
      dyOptions(useDataTimezone = TRUE)
```
